// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbaKRodcT3xwzwmSED5poJnS1l4_C7Lvs',
    appId: '1:330320867887:web:898c44ebaa80ba3c480cda',
    messagingSenderId: '330320867887',
    projectId: 'todo-897ca',
    authDomain: 'todo-897ca.firebaseapp.com',
    storageBucket: 'todo-897ca.appspot.com',
    measurementId: 'G-V8Q8VJ9C0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq0rQnmDV-DAbbY19gebeK_eB360J55zg',
    appId: '1:330320867887:android:69be3ba3e1477a5f480cda',
    messagingSenderId: '330320867887',
    projectId: 'todo-897ca',
    storageBucket: 'todo-897ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9PDp8UOzgO0QHOU8242afhyewVtDTXdM',
    appId: '1:330320867887:ios:f59cbafab74303e1480cda',
    messagingSenderId: '330320867887',
    projectId: 'todo-897ca',
    storageBucket: 'todo-897ca.appspot.com',
    iosClientId: '330320867887-gitej12fsvheeaqvsea59c3t9sghftv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppWithFirbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9PDp8UOzgO0QHOU8242afhyewVtDTXdM',
    appId: '1:330320867887:ios:f59cbafab74303e1480cda',
    messagingSenderId: '330320867887',
    projectId: 'todo-897ca',
    storageBucket: 'todo-897ca.appspot.com',
    iosClientId: '330320867887-gitej12fsvheeaqvsea59c3t9sghftv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppWithFirbase',
  );
}
